config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html\
  resources :stocks, except: [:show, :active]
  resources :investors
  resources :portfolios, except: [:new, :show]
  
  get "stocks/new", to: "stocks#new", as: "stock_new"

  get "/stocks/active", to: "stocks#active", as: "stock_active"
  get "/stocks/gainers", to: "stocks#gainers", as: "stock_gainers"
  get "/stocks/losers", to: "stocks#losers", as: "stock_losers"
  get "/stocks/volume", to: "stocks#volume", as: "stock_volume"
  get "/stocks/percent", to: "stocks#percent", as: "stock_percent"
  get "/stocks/:stockticker", to: "stocks#show", as: "stock_show"
  get "/portfolios/new/:ticker", to: "portfolios#new", as: "stock_buy"
  get "/portfolios/filledorders", to: "portfolios#filledorders", as: "stock_filled_orders"
  get "/portfolios/sell/:ticker", to: "portfolios#sell", as: "stock_sell"

  delete "/sessions/logout", to: 'sessions#logout', as: 'logout'
  get "/sessions/new", to: 'sessions#new', as: 'new_login'
  post '/sessions/login', to: 'sessions#login', as: 'login'

  # get "investors/new", to: "investors#new", as: "investors_new"
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
    belongs_to :investor
    belongs_to :stock
    after_initialize :init
    # validate :sold_quantity_cannot_be_greater_than_shares_held


def sold_quantity_cannot_be_greater_than_shares_held

end

# let's try to build a method that will output an array of the unique stocks and their avg price -- make new array
#for total. we want average price paid and # of shares
# if name isnt there, add it to the array. conditional inside: if it's a buy, then 
#if name is there
#stocks = [{"tesla" => 4, {"apple" => 3 }] using this instead of more hashes for ease of merge

@orders = Portfolio.all

    def self.unique_tickers(investor_id)
        
        stocklisting = []
        Portfolio.find_each do |trxn| #this gives us key value stock / quantity
            # byebug
            if trxn.investor_id == investor_id
                stock = {}
                if trxn.buysell
                    stock[trxn.stock.ticker] = trxn.quantity 
                else
                    stock[trxn.stock.ticker] = trxn.quantity * -1
                end
                stocklisting << stock
            end
        end
        stocklisting.inject{|a,b| a.merge(b){|_,x,y| x + y}} #this combines hashes with same name
    end

    def self.total_portfolio_purchase_price(current_investor)
        # @orders = Portfolio.all
        @total=0
        current_investor.portfolios.each do |t|
            if t.buysell #if stock is bought, this boolean is true
                p = t[:quantity] * t[:price]
                @total += p
            else
                p = t[:quantity] * t[:price] 
                @total -= p
            end
        end 
        
        @total
    end

    def self.total_portfolio_value(current_investor)
        # @orders = Portfolio.all
        self.api_client
        @total=0
        current_investor.portfolios.each do |t|
            if t.buysell #if stock is bought, this boolean is true
                
                p = t[:quantity] * @client.price(t.stock.ticker)
                @total += p
            else
                p = t[:quantity] * @client.price(t.stock.ticker) 
                @total -= p
            end
        end 
        @total
    end

    def self.cash(current_investor)
        # @cash = Portfolio.all 
        # byebug
        current_investor.portfolios.each do |t|
            @balance = t.cash_balance
        end 
        @balance - self.total_portfolio_purchase_price(current_investor)
    end

    def self.api_client
        @client = IEX::Api::Client.new(
            publishable_token: 'Tpk_28e84a02533f42b19d47d6545f0083c3',
            secret_token: 'secret_token',
            endpoint: 'https://sandbox.iexapis.com/v1'
        )
        
    end

    def init 
        self.cash_balance ||=10000
    end 

end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
    before_action :api_client
    before_action :unique_tickers
    before_action :find_portfolio, only: [:edit, :update]
    before_action :portfolio_vars, only: [:index, :show]

    def new
        @portfolio = Portfolio.new
    end

    def create 
        #this first part creates new stock db entry if not already there
        #look up stock, returns nill if not in db
        stock = Stock.all.find  {|stock| stock.ticker == params[:portfolio][:ticker]}
        if !stock   #if not in db, set params and create
            stock = Stock.create(ticker: params[:portfolio][:ticker])
        end
        
        # byebug
        #need to add stock id to portfolio creation params
        params[:portfolio][:stock_id] = stock.id


        #this is where validation goes
        # byebug
        #then we create the portfolio -- this step somehow creating a new stock object
        @current_investor.portfolios << Portfolio.create(portfolio_params)
        # byebug
        redirect_to portfolios_path
    end

    def index    
    end

    def show 
    end 

    def filledorders
       @positions =  @current_investor.portfolios
    end

    def sell
        @portfolio = Portfolio.new
        @positions = Portfolio.all
    end

    def edit 
    end 

    def update 
        @portfolio.update(portfolio_params)
        redirect_to portfolios_path 
    end 

    private 

    def portfolio_params
        params.require(:portfolio).permit(:stock_id, :price, :quantity, :buysell)
    end

    def api_client
        @client = IEX::Api::Client.new(
            publishable_token: 'Tpk_28e84a02533f42b19d47d6545f0083c3',
            secret_token: 'secret_token',
            endpoint: 'https://sandbox.iexapis.com/v1'
        )
    end

    def find_portfolio
        @portfolio = Portfolio.find(params[:id])
    end

    def unique_tickers
        @unique = Portfolio.unique_tickers(cookies[:investor_id].to_i)
    end

    def portfolio_vars
        # byebug
        @live_total = Portfolio.total_portfolio_value(@current_investor).round(2)
        @pp_total = Portfolio.total_portfolio_purchase_price(@current_investor) #want this to be for logged in user
        # byebug
        if @pp_total == 0
            @percent_change = 0
            @balance = 0
            @positions = 0
        else 
            @percent_change =  100 *(@live_total-@pp_total)/@pp_total
            @balance = Portfolio.cash(@current_investor)
            @positions = Portfolio.all
    end

    end

    # def user_positions #only selects position for the logged in user
    #     #may want to redo this, and use the relationships (has many, etc_) 
         
    #     position = [] #go though
    #     Portfolio.find_each do |trxn|
    #         if trxn.investor_id == cookies[:investor_id].to_i
    #             position << trxn
    #         end
    #     end
    #     position
    # end


    #for balances, etc: get cookies[investor:id], find the investor obj, Investor.Portfolio

end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/filledorders.html.erb
<div>
<h1 class="title">PAST FILLED ORDERS</h1>
<p><%= link_to 'Back to Portfolio', portfolios_path %>  </p>
<br><hr class="new1"><br>


    <% @positions.each do |t| %>
        <p>Stock: <%= t.stock.ticker %></p>
        <p>Price: $ <%= t[:price].to_f %></p>
            <% if t.buysell%>
                <p>Purchased: <%= t[:quantity] %> share(s) at <%=number_to_currency(t[:price])%></p>
                <p>Txn Net -<%= number_to_currency(t[:price] * t[:quantity]) %></p>
                <br><hr class="new1"><br>
            <%else%>
                <p>Share(s) Sold: <%= t[:quantity]  %></p>
                <p>Txn: +<%= number_to_currency(t[:price] * t[:quantity]) %></p>
                <br><hr class="new1"><br>
            <%end%>
    <%end%>

</div>

app/views/portfolios/index.html.erb
<!-- index through all the stocks held and list amount, want to only have unique and avg price-->
<!--if cookies[:investor_id] equals portfolio.investor_id-->
<div>
<h1 class="title">CURRENT PORTFOLIO</h1>
<br><hr class="new1"><br>

<%if @unique %>
    <% @unique.each do |key, value| %>
        <%if value != 0%>
            <p><%= link_to @client.company(key).company_name, stock_show_path(key)%><p>
            <p><%="Quantity #{value} - Current price: #{number_to_currency(@client.price(key))}"%></p>
            <p><%= link_to "buy", stock_buy_path(key)%>
            <%= link_to "sell", stock_sell_path(key)%> </p> 
            <br><hr class="new1"><br>
        <%end%>
    <%end%>
<%else%>
    <p>You currently own no stocks </p>
    <br><hr class="new1"><br>
<%end%>
<%if @unique %>
    <%if @unique.values.sum != 0%>
        <h3>Total purchase price: <%= number_to_currency(@pp_total) %></h3>
        <h3>Current value: <%= number_to_currency(@live_total) %></h3>     
        <h3>Total gain/loss: <%= number_to_percentage(@percent_change) %></h3>
        <h3>Cash Balance: <%= number_to_currency(@balance) %></h3>
        <br>
        <p><%= link_to 'Past Transactions', stock_filled_orders_path %></p>
        </div>
    <%else%>
        <h3>Current portfolio is empty.</h3><br>
        <h3>Cash Balance: <%= number_to_currency(@balance) %></h3>
    <%end%>
<%else%>
   <h3>Account Balance: $10,000 </h3> <!--hard coded, not ideal-->

<%end%>

<br>
<div>

app/views/portfolios/new.html.erb
<!--# Within here, stock will be added to portfolio. investor adds ticker, as well as quantity. -->
<!--this will save a transaction in portfolio (buy/sell, quantity, price, ticker)-->

<div>
<%@current_price = @client.quote(params[:ticker]).latest_price%>

<h2 class="title">Purchase shares of <%=@client.company(params[:ticker]).company_name%> </h2>

<h4>Current Price: <%=number_to_currency(@current_price)%> </h4>

<%=form_for @portfolio do |f|%>
    <%= f.label :quantity %>
    <%= f.number_field :quantity, min: 0 %><br><br>

    <%= f.hidden_field :buysell, value: true %>
    <%= f.hidden_field :price, value: @current_price.to_f %>
    <%= f.hidden_field :ticker, value: params[:ticker]%> <!--this hidden field to send ticker - then check in DB, if not already in db, create it-->

    <%= f.submit "Purchase Share(s)"%>
<%end%>
<br>
<br>
</div>

app/views/portfolios/sell.html.erb
<div>

<!--want to create validation. before able to sell, the :ticker that matches @unique must not surpass that int-->

<%@current_price = (@client.quote(params[:ticker]).latest_price)%>

<h2 class="title">Sell shares of <%=@client.company(params[:ticker]).company_name%> </h2>

<h4>Current Price: <%=number_to_currency(@current_price)%> </h4>
<%=form_for @portfolio do |f|%>
    <%= f.label :quantity %>
    <%= f.number_field :quantity, min: 0 %><br><br>

    <%= f.hidden_field :buysell, value: false %>
    <%= f.hidden_field :price, value: @current_price.to_f %>
    <%= f.hidden_field :ticker, value: params[:ticker]%> <!--this hidden field to send ticker - then check in DB, if not already in db, create it-->

    <%= f.submit "Sell Share(s)"%>
<%end%>
<br><br>
</div>

app/views/portfolios/show.html.erb
<div>
<h1 class="title">CURRENT HOLDINGS</h1>
<br><hr class="new1"><br>

<% @unique.each do |key, value| %>
    <%if value != 0%>
        <p><%= link_to @client.company(key).company_name, stock_show_path(key)%><p>
        <p><%="Quantity #{value} - Current price: $ #{@client.price(key)}"%></p>
        <p><%= link_to "buy", stock_buy_path(key)%>
        <%= link_to "sell", stock_sell_path(key)%> </p>
        <br><hr class="new1"><br>
    <%end%>
<%end%>

<h3>Total purchase price of stocks: <%= number_to_currency(@pp_total) %></h3>
<h3>Current value of stocks: <%= number_to_currency(@live_total) %></h3>

<h3>Total gain/loss <%= number_to_percentage(@percent_change) %></h3>
<h3>Cash Balance <%= number_to_currency(@balance) %></h3>
<br>
<p><%= link_to 'Past Transactions', stock_filled_orders_path %></p>
</div>