config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html\
  resources :stocks, except: [:show, :active]
  resources :investors
  resources :portfolios, except: [:new, :show]
  
  get "stocks/new", to: "stocks#new", as: "stock_new"

  get "/stocks/active", to: "stocks#active", as: "stock_active"
  get "/stocks/gainers", to: "stocks#gainers", as: "stock_gainers"
  get "/stocks/losers", to: "stocks#losers", as: "stock_losers"
  get "/stocks/volume", to: "stocks#volume", as: "stock_volume"
  get "/stocks/percent", to: "stocks#percent", as: "stock_percent"
  get "/stocks/:stockticker", to: "stocks#show", as: "stock_show"
  get "/portfolios/new/:ticker", to: "portfolios#new", as: "stock_buy"
  get "/portfolios/filledorders", to: "portfolios#filledorders", as: "stock_filled_orders"
  get "/portfolios/sell/:ticker", to: "portfolios#sell", as: "stock_sell"

  delete "/sessions/logout", to: 'sessions#logout', as: 'logout'
  get "/sessions/new", to: 'sessions#new', as: 'new_login'
  post '/sessions/login', to: 'sessions#login', as: 'login'

  # get "investors/new", to: "investors#new", as: "investors_new"
end

app/models/stock.rb
class Stock < ApplicationRecord
    has_many :portfolios
    has_many :investors, through: :portfolios

end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
    before_action :api_client
    skip_before_action :authorized

    def index
        lists
    end

    def new
        @stock = Stock.new
    end

    def create
        @stock = Stock.create(stock_params)
        redirect_to stock_buy_path(@stock.ticker)
    end

    def show  #shows individual stocks  
            if params[:search]
                if @client.price(params[:search]) != nil #an attempt at error handling
                    @key_stats = @client.key_stats(params[:search])
                    @company = @client.company(params[:search])
                    @news = @client.news(params[:search], 3)
                    @quote = @client.quote(params[:search])
                    @ticker = params[:search]
                else
                    redirect_to stocks_path
                end
            else
                    @key_stats = @client.key_stats(params[:stockticker])
                    @company = @client.company(params[:stockticker])
                    @news = @client.news(params[:stockticker], 3)
                    @quote = @client.quote(params[:stockticker])
                    @ticker = params[:stockticker]
            end   
    end

    def new
        @stock = Stock.new
        @number = Random.rand(500)
    end

    def create
        stock = Stock.create(stock_params)
        redirect_to stock_new_path 
    end 

    def active
        @active = @client.stock_market_list(:mostactive)
    end 

    def gainers 
        @gainers = @client.stock_market_list(:gainers)
    end 

    def losers
        @losers = @client.stock_market_list(:losers)
    end 

    def volume 
        @volume = @client.stock_market_list(:iexvolume)
    end

    def percent 
        @percent = @client.stock_market_list(:iexpercent)
    end 

    def lists
        # byebug
    end 

private
    def api_client
        @client = IEX::Api::Client.new(
            publishable_token: 'Tpk_28e84a02533f42b19d47d6545f0083c3',
            secret_token: 'secret_token',
            endpoint: 'https://sandbox.iexapis.com/v1'
        )
    end

    def stock_params
        params.require(:stock).permit(:ticker)
    end  
    
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/stocks/active.html.erb
<marquee class="back double size">
  <% @active.each do |stock| %>
    <%= stock.company_name %> - 
  <% end %>
</marquee>
<br>
<br>
<div>
<%= form_tag stock_show_path(:search), method: :get do %>
  <h1 class="cap title size3"><%= label_tag "Search Stocks By Symbol"%></h1>
  <br>
  <br>
  <%= search_field_tag :search %>
  <%= submit_tag("Search")  %>
 <%end%>
 <br>
 <br>
</div>
<br>
<div>
<h1 class="title">MOST ACTIVE</h1>
<br>  
<% @active.each do |stock|%>
  <p><%= link_to stock.company_name, stock_show_path(stock.symbol) %></p>
<%end%>
<br>
<br>
</div>

app/views/stocks/gainers.html.erb
<marquee class="back double size"> 
  <% @gainers.each do |stock| %>
    <%= stock.company_name %> - 
  <% end %>
</marquee>
<br>
<br>
<div>
<%= form_tag stock_show_path(:search), method: :get do %>
  <h1 class="cap title size3"><%= label_tag "Search Stocks By Symbol"%></h1>
  <br>
  <br>
  <%= search_field_tag :search %>
    <%= submit_tag("Search")  %>
 <%end%>
 <br>
 <br>
</div>
<br>
<div>
<h1 class="title">BIGGEST GAINERS</h1>
<br>
<% @gainers.each do |stock|%>
  <p><%= link_to stock.company_name, stock_show_path(stock.symbol) %></p>
<%end%>
<br>
<br>
</div>

app/views/stocks/index.html.erb
<!--form to choose gainers/losers-->
<div>
<%= form_tag stock_show_path(:search), method: :get do %>
  <h1 class="cap title size3"><%= label_tag "SEARCH STOCKS BY SYMBOL"%></h1>
  <br>
  <br>
  <%= search_field_tag :search %>
   <%= submit_tag("Search")  %>
 <%end%>
 <br>
 <br>
</div>
<br>
<div>
<h1 class="title">STOCK LISTS</h1>
<br>
<h3><%= link_to "Most Active", stock_active_path %></h3>
<br>
<h3><%= link_to "Biggest Gainers", stock_gainers_path %></h3>
<br>
<h3><%= link_to "Biggest Losers", stock_losers_path %></h3>
<br>
<h3><%= link_to "Highest Volume Today", stock_volume_path %></h3>
<br>
<h3><%= link_to "Largest Percentage Change", stock_percent_path %></h3>
<br>
<br>
</div>
<!-- search bar, sending same info back. form tag, repeat above-->

app/views/stocks/losers.html.erb
<marquee class="back double size">
  <% @losers.each do |stock| %>
    <%= stock.company_name %> - 
  <% end %>
</marquee>
<br>
<br>
<div>
<%= form_tag stock_show_path(:search), method: :get do %>
  <h1 class="cap title size3"><%= label_tag "Search Stocks By Symbol"%></h1>
  <br>
  <br>
  <%= search_field_tag :search %>
    <%= submit_tag("Search")  %>
 <%end%>
 <br>
 <br>
</div>
<br>
<div>
<h1 class="title">BIGGEST LOSERS</h1>
<br>
<% @losers.each do |stock|%>
  <p><%= link_to stock.company_name, stock_show_path(stock.symbol) %></p>
<%end%>
<br>
<br>
</div>

app/views/stocks/new.html.erb
<div>
<h3 class="title">Create Stock</h3>
  
<h4>Stock you want to add to list:</h4><br>

<%= form_for @stock do |f|%>
  <%= f.label :ticker %>
  <%= f.text_field :ticker%><br><br>

  <%=f.submit "add to watch" %>
<%end%>
</div>

app/views/stocks/percent.html.erb
<marquee class="back double size">
  <% @percent.each do |stock| %>
    <%= stock.company_name %> - 
  <% end %>
</marquee>
<br>
<br>
<div>
<%= form_tag stock_show_path(:search), method: :get do %>
  <h1 class="cap title size3"><%= label_tag "Search Stocks By Symbol"%></h1>
  <br>
  <br>
  <%= search_field_tag :search %>
    <%= submit_tag("Search")  %>
 <%end%>
 <br>
 <br>
</div>
<br>
<div>
<h1 class="size2 title">LARGEST PERCENTAGE CHANGE</h1>
<br>
<% @percent.each do |stock|%>
  <p><%= link_to stock.company_name, stock_show_path(stock.symbol) %></p>
<%end%>
<br>
<br>
</div>

app/views/stocks/show.html.erb
<marquee class="back double size"><%= @company.company_name %> - Trading at: $<%= @quote.latest_price %></marquee>
<br>
<br>
<div class="double">
<h1 class="title"><%= @company.company_name %></h1>
<h3><%= @ticker %></h3>
 <p>Price: $<%= @quote.latest_price %></p>
 <p>52 Week High: <%= number_to_currency(@key_stats.week_52_high) %></p>
 <p>52 Week Low: <%= number_to_currency(@key_stats.week_52_low) %></p>
 <p>Market Cap: <%= number_to_currency(@key_stats.market_cap) %></p>
 <p>EPS: <%= @key_stats.ttm_eps %></p>

 <%if  !@key_stats.dividend_yield == 0 %>
    <p>Dividend Yield: <%= @key_stats.dividend_yield %></p>
<%end%>

<%if cookies[:investor_id]%>
    <p><%= link_to "Purchase #{@ticker}", stock_buy_path(@ticker) %>  </p> 
    <p><%= link_to "Search Again", stocks_path %>  </p> 
<%else%>
    <p><%= link_to "Search Again", stocks_path %>  </p> 

 <%end%>
 <br>
 </div>

app/views/stocks/volume.html.erb
<marquee class="back double size">
  <% @volume.each do |stock| %>
    <%= stock.company_name %> - 
  <% end %>
</marquee>
<br>
<br>
<div>
<%= form_tag stock_show_path(:search), method: :get do %>
  <h1 class="cap title size3"><%= label_tag "Search Stocks By Symbol"%></h1>
  <br>
  <br>
  <%= search_field_tag :search %>
    <%= submit_tag("Search")  %>
 <%end%>
 <br>
 <br>
</div>
<br>
<div>
<h1 class="title">HIGHEST VOLUME</h1>
<br>
<% @volume.each do |stock|%>
  <p><%= link_to stock.company_name, stock_show_path(stock.symbol) %></p>
<%end%>
<br>
<br>
</div>