config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html\
  resources :stocks, except: [:show, :active]
  resources :investors
  resources :portfolios, except: [:new, :show]
  
  get "stocks/new", to: "stocks#new", as: "stock_new"

  get "/stocks/active", to: "stocks#active", as: "stock_active"
  get "/stocks/gainers", to: "stocks#gainers", as: "stock_gainers"
  get "/stocks/losers", to: "stocks#losers", as: "stock_losers"
  get "/stocks/volume", to: "stocks#volume", as: "stock_volume"
  get "/stocks/percent", to: "stocks#percent", as: "stock_percent"
  get "/stocks/:stockticker", to: "stocks#show", as: "stock_show"
  get "/portfolios/new/:ticker", to: "portfolios#new", as: "stock_buy"
  get "/portfolios/filledorders", to: "portfolios#filledorders", as: "stock_filled_orders"
  get "/portfolios/sell/:ticker", to: "portfolios#sell", as: "stock_sell"

  delete "/sessions/logout", to: 'sessions#logout', as: 'logout'
  get "/sessions/new", to: 'sessions#new', as: 'new_login'
  post '/sessions/login', to: 'sessions#login', as: 'login'

  # get "investors/new", to: "investors#new", as: "investors_new"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RagingBull</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

  <h1 class="head"><%= image_tag("output-onlinepngtools.png", size: "150x150") %><br>Raging Bull<br><br></h1>
      <ul class="nav">
      <% if @current_investor %>
          <li><%= link_to "Welcome #{@current_investor.name}", investor_path(@current_investor) %></li>
         <li><%= link_to "All Stocks", stocks_path %></li>
         <li><%= link_to "Portfolio", portfolios_path %></li>
         <li><%= link_to "Logout", logout_path, method: :delete  %></li>
      <%else%>
        <li><%= link_to "Stocks Main Page", stocks_path %></li>
         <li><%= link_to "Create Account", new_investor_path %></li>
        <li><%= link_to "Login", new_login_path %></li>
      <% end %>
      </ul>
      <br>
  
    <%= yield %>
  
  </body>
</html>